# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
       - name: Set environment variable
         run: |
            MY_VARIABLE="my_value"
            echo "export MY_VARIABLE=$MY_VARIABLE" >> ~/.bashrc
            source ~/.bashrc
       - name: Use environment variable
         run: echo $MY_VARIABLE


      
      
