# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
       - name: Set environment variable
         run: |
           echo "::set-env name=MY_VARIABLE::my_value"
       - name: Use environment variable
         run: echo $MY_VARIABLE



      
      
